version: 0.2

env:
  variables: {}
  parameter-store: {}

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Entered the install phase...
    finally:
      - echo Installation done
  build:
    commands:
      - echo Entered the build phase ...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - npm install
      - npm run-script build
    finally:
      - echo Building the HTML files finished
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - aws s3 sync public/ s3://$BUCKET --region us-east-1 --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths '/*'
artifacts:
  files: []
secondary-artifacts: {}
cache:
  paths: []