baseurl: http://devguidelines.s3-website-us-east-1.amazonaws.com/
disableKinds: ["section", "taxonomy", "taxonomyTerm", "404", "sitemap"]
googleAnalytics: "disabled"

module:
  mounts:
    - source: static
      target: static
    - source: assets/static/favicon-dev.ico
      target: static/favicon.ico
    - source: assets/static/robots-dev.txt
      target: static/robots.txt
    - source: node_modules/jquery/dist/jquery.slim.min.js
      target: static/js/jquery.slim.min.js
    - source: node_modules/jquery/dist/jquery.slim.min.map
      target: static/js/jquery.slim.min.map
    - source: node_modules/@trimbleinc/modus-bootstrap/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: static/js/bootstrap.bundle.min.js
    - source: node_modules/@trimbleinc/modus-bootstrap/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map
      target: static/js/bootstrap.bundle.min.js.map
    - source: node_modules/clipboard/dist/clipboard.min.js
      target: static/js/clipboard.min.js
    - source: node_modules/trimblewide-innersource/Resources
      target: static/innersource/Resources
